[package]
name = "true_and_false"
version = "0.1.0"
edition = "2021"
authors = [ "Richard W. Norton <rwtnorton@gmail.com>" ]

[dependencies]

[dev-dependencies]
assert_cmd = "2.0.13"
pretty_assertions = "1.4.0"
